### ISSUE TITLE
NoMethodError: undefined method `delete' for nil:NilClass

### ISSUE THREAD

**Issue by skddc** [5apps/liquor-cabinet#126]
https://sentry.io/5apps/liquor-cabinet/issues/622687002/

```
NoMethodError: undefined method `delete' for nil:NilClass
  lib/remote_storage/s3.rb:27:in `block in do_put_request'
    res.headers[:etag].delete('"'),
  lib/remote_storage/rest_provider.rb:439:in `deal_with_unauthorized_requests'
    block.call
  lib/remote_storage/s3.rb:19:in `do_put_request'
    deal_with_unauthorized_requests do
  lib/remote_storage/rest_provider.rb:146:in `put_data'
    etag, timestamp = do_put_request(url, data, content_type)
...
(35 additional frame(s) were not displayed)

NoMethodError: undefined method `delete' for nil:NilClass
```

**Comment by gregkare** [comment]
This one looks like a successful PUT that returned no ETag in the response headers

**Comment by skddc** [comment]
Yes, but how is that possible?
