### ISSUE TITLE
NoMethodError: undefined method `/' for nil:NilClass

### ISSUE THREAD

**Issue by galfert** [5apps/liquor-cabinet#128]
https://sentry.io/5apps/liquor-cabinet/issues/831346963/?referrer=github_plugin

```
NoMethodError: undefined method `/' for nil:NilClass
  lib/remote_storage/rest_provider.rb:496:in `block in get_directory_listing_from_redis_via_lua'
    v["Last-Modified"] = Time.at(v["Last-Modified"]/1000).httpdate
  lib/remote_storage/rest_provider.rb:495:in `each'
    items.reject{|k, _| k.end_with? "/"}.each do |_, v|
  lib/remote_storage/rest_provider.rb:495:in `get_directory_listing_from_redis_via_lua'
    items.reject{|k, _| k.end_with? "/"}.each do |_, v|
  lib/remote_storage/rest_provider.rb:97:in `get_directory_listing'
    items = get_directory_listing_from_redis_via_lua(user, directory)
...
(35 additional frame(s) were not displayed)

NoMethodError: undefined method `/' for nil:NilClass
```

**Comment by galfert** [comment]
Looks lie `v["Last-Modified"]` was `nil` in this case.
