### ISSUE TITLE
RestClient::InternalServerError: 500 Internal Server Error

### ISSUE THREAD

**Issue by raucao** [5apps/liquor-cabinet#141]
https://sentry.io/organizations/5apps/issues/1719689670/?referrer=github_plugin

```
RestClient::InternalServerError: 500 Internal Server Error
  lib/remote_storage/s3.rb:38:in `block in do_get_request'
    RestClient.get(url, authorization_headers.merge(headers), &block)
  lib/remote_storage/rest_provider.rb:449:in `deal_with_unauthorized_requests'
    block.call
  lib/remote_storage/s3.rb:34:in `do_get_request'
    deal_with_unauthorized_requests do
  lib/remote_storage/rest_provider.rb:70:in `get_data'
    res = do_get_request(url)
...
(44 additional frame(s) were not displayed)
```

**Comment by skddc** [comment]
Wondering if we should catch this and turn it into a 502 or something, or if we should just let it 500 to the user as is.
