### ISSUE TITLE
RestClient::Conflict: 409 Conflict

### ISSUE THREAD

**Issue by raucao** [5apps/liquor-cabinet#143]
https://sentry.io/organizations/5apps/issues/1930165541/?referrer=github_plugin

```
RestClient::Conflict: 409 Conflict
  lib/remote_storage/s3.rb:52:in `block in do_delete_request'
    RestClient.delete(url, authorization_headers)
  lib/remote_storage/rest_provider.rb:449:in `deal_with_unauthorized_requests'
    block.call
  lib/remote_storage/s3.rb:50:in `do_delete_request'
    deal_with_unauthorized_requests do
  lib/remote_storage/s3.rb:65:in `try_to_delete'
    do_delete_request(url) if found
  lib/remote_storage/rest_provider.rb:187:in `delete_data'
    found = try_to_delete(url)
...
(45 additional frame(s) were not displayed)
```

**Comment by skddc** [comment]
This might be the wrong repo to fix the issue. The back-end here is Exoscale's S3 API, but the solution to this one may be in the nginx config instead.
